# Enable Pyflakes and pycodestyle rules.
# see https://github.com/charliermarsh/ruff#supported-rules
# F = Pyflakes
# E,W = pycodestyle
# N = pep8-naming
# UP = pyupgrade
# B = bugbear
# PTH = flake8-use-pathlib
# PL = pylint
lint.select = ["E", "F", "W", "N", "RUF", "I001", "UP", "B", "PTH", "PL"]
# E501: line too long
lint.ignore = ["E501"]
fix = true
line-length = 120
target-version = "py313"
extend-include = [".CMakePresets.json.in", "docs/conf.py.in"]

[lint.per-file-ignores]
# ignore magic numbers in test sources (matches clang-tidy setup for tests/*)
"tests/python/*" = ["PLR2004"]
